name: Publish jardindechampagne
on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [publish-event]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CTFL_SPACE }}
          CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CTFL_ACCESSTOKEN }}


      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.OVH_URL }}
          username: ${{ secrets.OVH_USER }}
          password: ${{ secrets.OVH_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./www/
